### PR TITLE
fix : add network type inside `getinfo`

### LINKED ISSUE #183: Add network type in getinfo
It would be pretty good to add the network type in the `getinfo` command.

### PR DESCRIPTION
**Pull request by Harshit933**
We simply get the network from `conf` inside the `CoreWalletManager`. Thus, adding a function inside `CoreWalletManager` to return the chain of network the wallet is built upon.

fixes #183

### CODE REVIEW

File: lampod/src/ln/inventory_manager.rs [hunk 1]
```diff
@@ -32,10 +32,17 @@ impl InventoryHandler for LampoInventoryManager {
 
         match event {
             InventoryCommand::GetNodeInfo(chan) => {
+                let chain = self
+                    .channel_manager
+                    .onchain()
+                    .wallet_manager
+                    .get_network_type()
+                    .unwrap();
```
Comment (vincenzopalazzo) [inline lampod/src/ln/inventory_manager.rs:40]: why did we need to unwrap?

File: lampod/src/ln/channel_manager.rs [hunk 2]
```diff
@@ -194,6 +194,10 @@ impl LampoChannelManager {
         self.channeld.clone().unwrap()
     }
 
+    pub fn onchain(&self) -> Arc<LampoChainManager> {
+        self.onchain.clone()
+    }
```
Comment (vincenzopalazzo) [inline lampod/src/ln/channel_manager.rs:199]: Why?

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
Thanks for this, but I think you can access the network directory from the lampo configuration that it is inside the lampod struct?

Or I am missing something?

**Comment by Harshit933** [comment]
> Thanks for this, but I think you can access the network directory from the lampo configuration that it is inside the lampod struct?
> 
> Or I am missing something?

Actually I missed to see conf inside `LampoChannelManager`. Thanks for the review.

File: lampod/src/ln/inventory_manager.rs [hunk 3]
```diff
@@ -32,10 +32,12 @@ impl InventoryHandler for LampoInventoryManager {
 
         match event {
             InventoryCommand::GetNodeInfo(chan) => {
+                let chain = self.channel_manager.conf().network.to_string();
```
Comment (vincenzopalazzo) [inline lampod/src/ln/inventory_manager.rs:35]:
```suggestion
                let chain = self.channel_manager.conf.network.to_string();
```

if you can not do that, try `pub (crate) conf`

File: lampod/src/ln/channel_manager.rs [hunk 4]
```diff
@@ -406,6 +406,10 @@ impl LampoChannelManager {
         )));
         Ok(())
     }
+
+    pub fn conf(&self) -> LampoConf {
+        self.conf.clone()
+    }
```
Comment (vincenzopalazzo) [inline lampod/src/ln/channel_manager.rs:412]: imho we do not need it :)

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
we can still do better 😄

**Review by vincenzopalazzo — APPROVED** [review]
LGMT, thanks
