### PR TITLE
Fixes stuff inside bolt12 decode

### LINKED ISSUE #270: [BUG] bolt12 decode does not include the blinded path inside the offer if specified
### Description

bolt12 decode does not include the blinded path inside the offer if specified 

---

### Steps to Reproduce

```
➜  ~ lampo-cli --network signet decode --invoice_str lno1qgsyxjtl6luzd9t3pr62xr7eemp6awnejusgf6gw45q75vcfqqqqqqqsespexwyy4tcadvgg89l9aljus6709kx235hhqrk6n8dey98uyuftzdqzrtkahuum7m56dxlnx8r6tffy54004l7kvs7pylmxx7xs4n54986qyqeeuhhunayntt50snmdkq4t7fzsgghpl69v9csgparek8kv7dlp5uqr8ymp5s4z9upmwr2s8xu020d45t5phqc8nljrq8gzsjmurzevawjz6j6rc95xwfvnhgfx6v4c3jha7jwynecrz3y092nn25ek4yl7xp9yu9ry9zqagt0ktn4wwvqg52v9ss9ls22sqyqqestzp2l6decpn87pq96udsvx
{
  "issuer_id": null,
  "expiry_time": null,
  "description": null,
  "routes": [],
  "hints": [],
  "network": "testnet",
  "amount_msa": null
}
```

### PR DESCRIPTION
**Pull request by Harshit933**
Decoding bolt12 now:

```
[harshit:~] lampo-cli --network regtest decode --invoice_str lno1qgsyxjtl6luzd9t3pr62xr7eemp6awnejusgf6gw45q75vcfqqqqqqqsespexwyy4tcadvgg89l9aljus6709kx235hhqrk6n8dey98uyuftzdqzrtkahuum7m56dxlnx8r6tffy54004l7kvs7pylmxx7xs4n54986qyqeeuhhunayntt50snmdkq4t7fzsgghpl69v9csgparek8kv7dlp5uqr8ymp5s4z9upmwr2s8xu020d45t5phqc8nljrq8gzsjmurzevawjz6j6rc95xwfvnhgfx6v4c3jha7jwynecrz3y092nn25ek4yl7xp9yu9ry9zqagt0ktn4wwvqg52v9ss9ls22sqyqqestzp2l6decpn87pq96udsvx
{
  "issuer": "No issuer id provided",
  "offer_id": "[52, 70, 8, 105, 84, 158, 55, 116, 140, 234, 171, 220, 255, 98, 132, 169, 130, 102, 193, 128, 82, 171, 42, 126, 158, 181, 161, 175, 10, 94, 91, 125]",
  "offer_chains": [
    "43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000"
  ],
  "description": "Description not provided",
  "offer_paths": [
    {
      "blinded_hops": [
        "0339e5efc9f4935ae8f84f6db02abf2450422e1fe8ac2e2080f479b1eccf37e1a7",
        "031448f2aa7355336a93fe304a4e14642881d42df65ceae73008a2985840bf8295"
      ],
      "blinding_points": "021aeddbf39bf6e9a69bf331c7a5a524a55efaffd6643c127f66378d0ace9529f4"
    }
  ],
  "network": "testnet"
}
```

If the bolt11/bolt12 is invalid:
```
[harshit:~] lampo-cli --network regtest decode --invoice_str lno1qgsyxjtl6luzd9t3pr62xr7eemp6awnejusgf6gw45q75vcfqqqqqqqsespexwyy4tcadvgg89l9aljus6709kx235hhqrk6n8dey98uyuftzdqzrtkahuum7m56dxlnx8r6tffy54004l7kvs7pylmxx7xs4n54986qyqeeuhhunayntt50snmdkq4t7fzsgghpl69v9csgparek8kv7dlp5uqr8ymp5s4z9upmwr2s8xu020d45t5phqc8nljrq8gzsjmurzevawjz6j6rc95xwfvnhgfx6v4c3jha7jwynecrz3y092nn25ek4yl7xp9yu9ry9zqagt0ktn4wwvqg52v9ss9ls22sqyqqestzp2l6decpn87pq96uds
{
  "code": -1,
  "message": "Not able to decode invoice",
  "data": null
}
```

UPDATE:

Running `lampo-cli --network regtest decode --invoice_str lno1qgsyxjtl6luzd9t3pr62xr7eemp6awnejusgf6gw45q75vcfqqqqqqqsespexwyy4tcadvgg89l9aljus6709kx235hhqrk6n8dey98uyuftzdqzrtkahuum7m56dxlnx8r6tffy54004l7kvs7pylmxx7xs4n54986qyqeeuhhunayntt50snmdkq4t7fzsgghpl69v9csgparek8kv7dlp5uqr8ymp5s4z9upmwr2s8xu020d45t5phqc8nljrq8gzsjmurzevawjz6j6rc95xwfvnhgfx6v4c3jha7jwynecrz3y092nn25ek4yl7xp9yu9ry9zqagt0ktn4wwvqg52v9ss9ls22sqyqqestzp2l6decpn87pq96udsvx`

Gives the following output:
```
{
  "issuer_id": null,
  "offer_id": "34460869549e37748ceaabdcff6284a98266c18052ab2a7e9eb5a1af0a5e5b7d",
  "offer_chains": [
    "43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000"
  ],
  "description": null,
  "offer_paths": [
    {
      "blinded_hops": [
        "0339e5efc9f4935ae8f84f6db02abf2450422e1fe8ac2e2080f479b1eccf37e1a7",
        "031448f2aa7355336a93fe304a4e14642881d42df65ceae73008a2985840bf8295"
      ],
      "blinding_points": "021aeddbf39bf6e9a69bf331c7a5a524a55efaffd6643c127f66378d0ace9529f4"
    }
  ],
  "network": "testnet"
}
```
See commits for more info.
Fixes #270 #318

### CODE REVIEW

File: lampod/src/jsonrpc/offchain.rs [hunk 1]
```diff
@@ -80,40 +79,69 @@ pub fn json_decode_invoice(ctx: &LampoDaemon, request: &json::Value) -> Result<j
...
+            .unwrap_or_else(|| "No issuer id provided".to_string());
+
+        let bolt12_invoice = Bolt12InvoiceInfo {
+            offer_id,
+            network: network.unwrap().to_string(),
+            description: desc,
+            offer_chains: chains,
+            offer_paths: paths,
+            issuer: issuer_id,
+        };
```
Comment (vincenzopalazzo) [inline lampod/src/jsonrpc/offchain.rs:136]: Do you think that it is possible to implement the `From<ldk::Bolt12Offer> for Bolt12InvoiceInfo`? IDK what is the ldk type name bit should be good to have something like `let bolt12invoice = offer.info()`

File: lampod/src/jsonrpc/offchain.rs [hunk 2]
```diff
@@ -80,40 +79,69 @@ pub fn json_decode_invoice(ctx: &LampoDaemon, request: &json::Value) -> Result<j
...
+        let offer_id = format!("{:?}", offer.id().0);
+        let desc = offer
+            .description()
+            .map(|desc| desc.to_string())
+            .unwrap_or_else(|| "Description not provided".to_string());
+
+        let issuer_id = offer
+            .issuer()
+            .map(|issuer| issuer.to_string())
+            .unwrap_or_else(|| "No issuer id provided".to_string());
```
Comment (vincenzopalazzo) [inline lampod/src/jsonrpc/offchain.rs:127]: When a type is None, do not force to be not none. Keep it `Option` otherwise the user of our API need to check the ID.

If there is no description, leave it None.

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]

**Comment by vincenzopalazzo** [comment]
Plus `offer_id` is a vector of bytes, please convert it to `hex::(offer_id)` there is no need to print a vector of byte to the user

File: lampod/src/jsonrpc/offchain.rs (hunk 1 above)
Comment (Harshit933) [reply lampod/src/jsonrpc/offchain.rs]: Done inside d7ceae28b8acaf599a2e158ca7317844357e295b

File: lampod/src/jsonrpc/offchain.rs (hunk 2 above)
Comment (Harshit933) [reply lampod/src/jsonrpc/offchain.rs]: Done d7ceae28b8acaf599a2e158ca7317844357e295b

**Comment by vincenzopalazzo** [comment]
@Harshit933 can you post another time the `lampo-cli --network regtest decode --invoice_str lno1qgsyxjtl6luzd9t3pr62xr7eemp6awnejusgf6gw45q75vcfqqqqqqqsespexwyy4tcadvgg89l9aljus6709kx235hhqrk6n8dey98uyuftzdqzrtkahuum7m56dxlnx8r6tffy54004l7kvs7pylmxx7xs4n54986qyqeeuhhunayntt50snmdkq4t7fzsgghpl69v9csgparek8kv7dlp5uqr8ymp5s4z9upmwr2s8xu020d45t5phqc8nljrq8gzsjmurzevawjz6j6rc95xwfvnhgfx6v4c3jha7jwynecrz3y092nn25ek4yl7xp9yu9ry9zqagt0ktn4wwvqg52v9ss9ls22sqyqqestzp2l6decpn87pq96udsvx`

And/or probably write a test to make sure that what we should have as a hex string it is not a vector of bytes?

otherwise LGMT Thanks :)

**Comment by Harshit933** [comment]
> @Harshit933 can you post another time the `lampo-cli --network regtest decode --invoice_str lno1qgsyxjtl6luzd9t3pr62xr7eemp6awnejusgf6gw45q75vcfqqqqqqqsespexwyy4tcadvgg89l9aljus6709kx235hhqrk6n8dey98uyuftzdqzrtkahuum7m56dxlnx8r6tffy54004l7kvs7pylmxx7xs4n54986qyqeeuhhunayntt50snmdkq4t7fzsgghpl69v9csgparek8kv7dlp5uqr8ymp5s4z9upmwr2s8xu020d45t5phqc8nljrq8gzsjmurzevawjz6j6rc95xwfvnhgfx6v4c3jha7jwynecrz3y092nn25ek4yl7xp9yu9ry9zqagt0ktn4wwvqg52v9ss9ls22sqyqqestzp2l6decpn87pq96udsvx`

Updated the description also added a test in 593fe3ef0188caf7ab2befb791b89d6269025c49

File: lampod/src/jsonrpc/offchain.rs [hunk 3]
```diff
@@ -80,40 +79,69 @@ pub fn json_decode_invoice(ctx: &LampoDaemon, request: &json::Value) -> Result<j
...
+                    .blinded_hops
+                    .iter()
+                    .map(|node| node.blinded_node_id.to_string())
+                    .collect::<Vec<String>>(),
+                blinding_points: path.blinding_point.to_string(),
+            })
+            .collect::<Vec<BlindedPath>>();
+
+        //FIXME: Convert this to hex
+        let offer_id = format!("{:?}", offer.id().0);
```
Comment (vincenzopalazzo) [inline lampod/src/jsonrpc/offchain.rs]: Ok this is still not correct!

Something like ` let offer_id = hex::encode(offer.id().0);` should work.

If you change this part of the code later, you should rework the commit history

File: lampod/src/jsonrpc/offchain.rs [hunk 4]
```diff
@@ -80,40 +79,69 @@ pub fn json_decode_invoice(ctx: &LampoDaemon, request: &json::Value) -> Result<j
...
+        let desc = offer
+            .description()
+            .map(|desc| desc.to_string())
+            .unwrap_or_else(|| "Description not provided".to_string());
```
Comment (vincenzopalazzo) [inline lampod/src/jsonrpc/offchain.rs]: The description needs to be None if it is not provided. what happens if someone put the string `Description not provide` inside the description?

Please use Rust as a properly typed language

File: lampod/src/jsonrpc/offchain.rs (hunk 2 above)
Comment (vincenzopalazzo) [inline lampod/src/jsonrpc/offchain.rs]: same here, so this commit should be reworked if you change it later

File: lampo-common/src/model/invoice.rs [hunk 5]
```diff
@@ -72,14 +73,57 @@ pub mod response {
...
+                .chains()
+                .iter()
+                .map(|chain| chain.to_string())
+                .collect::<Vec<String>>();
+
+            let network = offer
+                .chains()
+                .first()
+                .map(|hash| Network::from_chain_hash(*hash))
+                .unwrap_or(Some(Network::Bitcoin));
```
Comment (vincenzopalazzo) [inline lampo-common/src/model/invoice.rs:96]: Add a reference to the bolts where it is telling that if the chain is none the network is implied to bitcoin

File: lampo-common/src/model/invoice.rs [hunk 6]
```diff
@@ -72,14 +73,57 @@ pub mod response {
...
+        pub issuer_id: Option<String>,
         pub offer_id: String,
         pub offer_chains: Vec<String>,
-        pub description: String,
+        pub description: Option<String>,
         pub offer_paths: Vec<BlindedPath>,
         pub network: String,
     }
 
+    impl From<LDKOffer> for Bolt12InvoiceInfo {
```
Comment (vincenzopalazzo) [inline lampo-common/src/model/invoice.rs:84]: Nice trick!

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
Ok I did another  review, thanks for doing it.

I think the git history need some kind of rework (squash the commit with the one that are no longer true) and then we are ready to go :)

Thanks for doing it

File: lampod/src/jsonrpc/offchain.rs (hunk 3 above)
Comment (Harshit933) [reply lampod/src/jsonrpc/offchain.rs]: This was done previously, but I cleaned up the git history now.

File: lampod/src/jsonrpc/offchain.rs (hunk 4 above)
Comment (Harshit933) [reply lampod/src/jsonrpc/offchain.rs]: This was also fixed inside 68d57c905baedf14224e5bcafed8cd088fcb6d06

File: lampo-common/src/model/invoice.rs (hunk 5 above)
Comment (Harshit933) [reply lampo-common/src/model/invoice.rs:97]: Done inside 68d57c905baedf14224e5bcafed8cd088fcb6d06

File: lampo-testing/src/lib.rs [hunk 7]
```diff
@@ -116,9 +116,7 @@ impl LampoTesting {
         server.add_rpc("funds", json_funds).unwrap();
         server.add_rpc("invoice", json_invoice).unwrap();
         server.add_rpc("offer", json_offer).unwrap();
-        server
-            .add_rpc("decode_invoice", json_decode_invoice)
-            .unwrap();
+        server.add_rpc("decode", json_decode_invoice).unwrap();
```
[the remark this answers is not in the document]
Comment (Harshit933) [reply lampo-testing/src/lib.rs:119]: Done inside ea1fcf31367af1008ea14d8a58c687efb35a5140

File: tests/tests/src/lampo_tests.rs [hunk 8]
```diff
@@ -505,10 +505,28 @@ pub fn decode_offer() -> error::Result<()> {
...
+    let decode: response::Bolt12InvoiceInfo = node1.lampod().call(
+        "decode",
+        request::DecodeInvoice {
+            invoice_str: "lno1qgsyxjtl6luzd9t3pr62xr7eemp6awnejusgf6gw45q75vcfqqqqqqqsespexwyy4tcadvgg89l9aljus6709kx235hhqrk6n8dey98uyuftzdqzrtkahuum7m56dxlnx8r6tffy54004l7kvs7pylmxx7xs4n54986qyqeeuhhunayntt50snmdkq4t7fzsgghpl69v9csgparek8kv7dlp5uqr8ymp5s4z9upmwr2s8xu020d45t5phqc8nljrq8gzsjmurzevawjz6j6rc95xwfvnhgfx6v4c3jha7jwynecrz3y092nn25ek4yl7xp9yu9ry9zqagt0ktn4wwvqg52v9ss9ls22sqyqqestzp2l6decpn87pq96udsvx".to_string(),
+        },
+    )?;
+
+    // Checks if all the character inside the offer_id is hex.
+    let res = decode.offer_id.chars().all(|c| c.is_ascii_hexdigit());
+    assert!(res);
```
[the remark this answers is not in the document]
Comment (Harshit933) [reply tests/tests/src/lampo_tests.rs:534]: Done inside 6a02c694bbab9c52dcc5e3e451c01e523a023c0d

File: lampo-common/src/model/invoice.rs [hunk 9]
```diff
@@ -70,6 +71,66 @@ pub mod response {
...
+
+    impl From<LDKOffer> for Bolt12InvoiceInfo {
+        fn from(offer: LDKOffer) -> Self {
+            let chains = offer
+                .chains()
+                .iter()
+                .map(|chain| chain.to_string())
+                .collect::<Vec<String>>();
+
+            // Reference: https://github.com/lightning/bolts/blob/master/12-offer-encoding.md
```
Comment (vincenzopalazzo) [inline lampo-common/src/model/invoice.rs:92]:
```rust
// Reference: https://github.com/lightning/bolts/blob/master/12-offer-encoding.md#requirements-for-offers
// if the chain for the invoice is not solely bitcoin:
// MUST specify offer_chains the offer is valid for.
// otherwise:
// SHOULD omit offer_chains, implying that bitcoin is only chain.
```

Better quote the spec in this way you know if this code is outdated when and if some part of the spec change.

File: lampo-common/src/model/invoice.rs [hunk 10]
```diff
@@ -70,6 +71,66 @@ pub mod response {
...
+            let network = offer
+                .chains()
+                .first()
+                .map(|hash| Network::from_chain_hash(*hash))
+                .unwrap_or(Some(Network::Bitcoin));
```
Comment (vincenzopalazzo) [inline lampo-common/src/model/invoice.rs:97]: we can find a way to return the following `.unwrap_or(Network::Bitcoin);`

In this way we avoid the unwrap down in the code!

File: lampod/src/jsonrpc/offchain.rs [hunk 11]
```diff
@@ -80,40 +77,24 @@ pub fn json_decode_invoice(ctx: &LampoDaemon, request: &json::Value) -> Result<j
...
-        unreachable!()
-    };
-
-    Ok(json::to_value(&invoice)?)
+        Err(Error::Rpc(RpcError {
+            code: -1,
+            message: "Not able to decode invoice".to_string(),
+            data: None,
+        }))
+    }
```
Comment (vincenzopalazzo) [inline lampod/src/jsonrpc/offchain.rs:97]: Do we have an `error!` macros to use?

File: lampo-testing/src/lib.rs (hunk 7 above)
Comment (vincenzopalazzo) [inline lampo-testing/src/lib.rs:119]: wondering if we need to change this also in the `lampod-cli`

**Review by vincenzopalazzo — COMMENTED** [review]
Concept ACK 6a02c694bbab9c52dcc5e3e451c01e523a023c0d

Small comments on the code still, but we are good to go! thanks for working on it

File: lampod/src/jsonrpc/offchain.rs (hunk 11 above)
Comment (Harshit933) [reply lampod/src/jsonrpc/offchain.rs:97]: Fixed

File: lampo-common/src/model/invoice.rs (hunk 10 above)
Comment (Harshit933) [reply lampo-common/src/model/invoice.rs:97]: Fixed

File: lampo-common/src/model/invoice.rs (hunk 9 above)
Comment (Harshit933) [reply lampo-common/src/model/invoice.rs]: Done

File: lampo-common/src/model/invoice.rs [hunk 12]
```diff
@@ -89,12 +89,16 @@ pub mod response {
...
+            // MUST specify offer_chains the offer is valid for.
+            // otherwise:
+            // SHOULD omit offer_chains, implying that bitcoin is only chain.
             let network = offer
                 .chains()
                 .first()
-                .map(|hash| Network::from_chain_hash(*hash))
-                .unwrap_or(Some(Network::Bitcoin));
+                .and_then(|hash| Network::from_chain_hash(*hash))
+                .or(Some(Network::Bitcoin));
```
Comment (vincenzopalazzo) [inline lampo-common/src/model/invoice.rs:101]: Good also for a folloup PR, but I would like to leave this Optional and not try to force the type here!

If there is any `chain`, will remain `None`

File: tests/tests/src/lampo_tests.rs [hunk 13]
```diff
@@ -509,3 +509,28 @@ pub fn decode_offer() -> error::Result<()> {
...
+        },
+    )?;
+
+    assert_eq!(
+        decode.offer_id,
+        "34460869549e37748ceaabdcff6284a98266c18052ab2a7e9eb5a1af0a5e5b7d"
+    );
+    // Checks if all the character inside the offer_id is hex.
+    let res = decode.offer_id.chars().all(|c| c.is_ascii_hexdigit());
+    assert!(res);
```
Comment (vincenzopalazzo) [inline tests/tests/src/lampo_tests.rs:534]: we can remove this code, I do not understand it, so better remove it (also in a follup PR)

**Review by vincenzopalazzo — APPROVED** [review]
LGTM
