### PR TITLE
Wait for `OnChainEvent::SendRawTransaction` before returning from `fundchannel` RPC call

### LINKED ISSUE #174: lampo-jsonrpc: do not returnt the errors back to the commands
when I open a channel I get the following information in the log, but the command does not return any error response

```
2023-12-24T13:46:26.053Z DEBUG jsonrpc {"unnamed": [Response { result: Some(Object {"node_id": String("03cdc5ce9df1e05653a1f2db9e29bad1a1c81940315dd16e66216803aac07423aa"), "amount": Number(10000), "public": Bool(true), "push_mst": Number(0), "to_self_delay": Number(2016), "tx": Null}), error: None, id: Str("0"), jsonrpc: "2.0" }]}. [lampo-jsonrpc/src/lib.rs:149]
2023-12-24T13:46:26.067Z DEBUG ldk lightning::ln::peer_handler:1931 DEBUG Handling SendOpenChannel event in peer_handler for node 03cdc5ce9df1e05653a1f2db9e29bad1a1c81940315dd16e66216803aac07423aa for channel 90dfe394b6d67f6340a43452c10868860f239beb80ed0d4bf5717a0126b9747b. [lampod/src/utils/logger.rs:46]
2023-12-24T13:46:26.137Z DEBUG ldk lightning::ln::peer_handler:1600 DEBUG Got Err message from 03cdc5ce9df1e05653a1f2db9e29bad1a1c81940315dd16e66216803aac07423aa: Peer's feerate much too high. Actual: 1108. Our expected upper limit: 253. [lampod/src/utils/logger.rs:46]
2023-12-24T13:46:26.137Z ERROR ldk lightning::ln::channelmanager:2806 ERROR Force-closing channel 90dfe394b6d67f6340a43452c10868860f239beb80ed0d4bf5717a0126b9747b. [lampod/src/utils/logger.rs:49]
2023-12-24T13:46:26.137Z DEBUG ldk lightning::ln::channelmanager:2750 DEBUG Finishing force-closure of channel with 0 HTLCs to fail. [lampod/src/utils/logger.rs:46]
```

### PR DESCRIPTION
**Pull request by tareknaser**
Fixes #174
## Changes:
- Modified `OpenChannel` response struct of `fundchannel` JSON-RPC call to include the funding transaction of type `bitcoin::Transaction` 
- Wait for the `OnChainEvent::SendRawTransaction` event before returning from the JSON-RPC call of `fundchannel`. The timeout is 30 seconds.

### CODE REVIEW

File: lampo-common/src/model/open_channel.rs [hunk 1]
```diff
@@ -30,9 +30,9 @@ pub mod response {
 
     use serde::{Deserialize, Serialize};
 
-    use crate::bitcoin::OutPoint;
     use crate::error;
     use crate::types::NodeId;
+    use bitcoin::Transaction;
```
Comment (vincenzopalazzo) [inline lampo-common/src/model/open_channel.rs:35]:
```suggestion
    use carte::bitcoin::Transaction;
```

File: lampod/src/jsonrpc/open_channel.rs [hunk 2]
```diff
@@ -10,6 +10,9 @@ use crate::LampoDeamon;
 pub fn json_open_channel(ctx: &LampoDeamon, request: &json::Value) -> Result<json::Value, Error> {
     log::info!("call for `openchannel` with request {:?}", request);
     let request: request::OpenChannel = json::from_value(request.clone())?;
+
+    // LDK's `create_channel()` doesn't check if you are currently connected
+    // to the given peer so we need to check ourselves
     // FIXME: remove unwrap!
```
Comment (vincenzopalazzo) [inline lampod/src/jsonrpc/open_channel.rs:16]: Someone that `FIXME` this will also fix some of the issues that we have open

File: lampod/src/ln/channel_manager.rs [hunk 3]
```diff
@@ -426,13 +426,24 @@ impl ChannelEvents for LampoChannelManager {
...
+
+        // Wait for SendRawTransaction to be received so to get the funding transaction
+        let tx: Option<Transaction> = loop {
+            let events = self.handler().events();
+            let event = events.recv_timeout(std::time::Duration::from_secs(30))?;
+
+            if let Event::OnChain(OnChainEvent::SendRawTransaction(tx)) = event {
+                break Some(tx);
+            }
+        };
```
Comment (vincenzopalazzo) [inline lampod/src/ln/channel_manager.rs:438]: We just need a fixme here that tell us that we can going looping forever, currently a fixme is fine

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
LGTM, just adding some comments while waiting for the CI

File: lampod/src/ln/channel_manager.rs (hunk 3 above)
Comment (tareknaser) [reply lampod/src/ln/channel_manager.rs:439]: Good catch. Thank you

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/vincenzopalazzo/lampo.rs/pull/197/commits/9480a3e4dd5d90cc53c763aa1ecd1bcc22d0c773
